// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsi96Em_9WG0Ifu3imWy5qo5T0UKDmyxs',
    appId: '1:441493633209:web:f1b7bb44dfe02ec60c0368',
    messagingSenderId: '441493633209',
    projectId: 'gitali2',
    authDomain: 'gitali2.firebaseapp.com',
    storageBucket: 'gitali2.firebasestorage.app',
    measurementId: 'G-Q6H31LGMGW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6NGEELj90WTj83Fsu6Eh1j9WZolt3U3M',
    appId: '1:441493633209:android:51d149bfb50c1f1d0c0368',
    messagingSenderId: '441493633209',
    projectId: 'gitali2',
    storageBucket: 'gitali2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChhbzomZ4glQb8mhNawg2-uZfpqnIIzM0',
    appId: '1:441493633209:ios:ca4e4c9243f234cc0c0368',
    messagingSenderId: '441493633209',
    projectId: 'gitali2',
    storageBucket: 'gitali2.firebasestorage.app',
    iosBundleId: 'com.example.gitali2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChhbzomZ4glQb8mhNawg2-uZfpqnIIzM0',
    appId: '1:441493633209:ios:ca4e4c9243f234cc0c0368',
    messagingSenderId: '441493633209',
    projectId: 'gitali2',
    storageBucket: 'gitali2.firebasestorage.app',
    iosBundleId: 'com.example.gitali2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsi96Em_9WG0Ifu3imWy5qo5T0UKDmyxs',
    appId: '1:441493633209:web:ed7125401ba198ae0c0368',
    messagingSenderId: '441493633209',
    projectId: 'gitali2',
    authDomain: 'gitali2.firebaseapp.com',
    storageBucket: 'gitali2.firebasestorage.app',
    measurementId: 'G-B0DH5ZS9YL',
  );
}
